[tool.ruff]
line-length = 88
indent-width = 4
lint.ignore = [
       "F405"   # allow * imports
]

# import sorting settings (replaces isort)
[tool.ruff.lint.isort]
force-single-line = false
force-sort-within-sections = true
known-first-party = ["custom_components"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
force-to-top = ["logging"]

[tool.ruff.format]
quote-style = "single" # Use a single quote instead of double

[tool.pycln]
all = true

[tool.refurb]
python_version = "3.11"
quiet = true
ignore = [ "FURB109","FURB184" ]
